name: adscoin
description: ads coin app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.12.1
  intl: ^0.16.0
  onesignal_flutter: ^2.2.0
  provider: ^4.3.2+4
  path_drawing: "^0.4.1"
  jwt_decoder: ^2.0.1
  shared_preferences: ^0.5.12+4
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_icons: ^1.1.0
  flutter_staggered_grid_view: ^0.3.0
  smooth_star_rating: 1.1.1
  image_picker: ^0.6.7+12
  flutter_screen_scaler: ^2.0.0
  flutter_html:
  getwidget: ^2.0.3
  shimmer: ^1.1.2
  html_editor_enhanced:
  sqflite: ^1.3.1+1
  share: ^2.0.4
  url_launcher: ^5.7.10
  dio: ^3.0.10

#  social_share: 2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/img/"
    - "assets/img/png/"
    - "assets/img/svg/"
